### ISSUE TITLE
[PATCH] Fix spelling error in manpage

### ISSUE THREAD

**Issue by carnil** [gnustavo/SVN-Hooks#10]
In Debian we are currently applying the following patch to SVN-Hooks.
We thought you might be interested in it too.

    Description: Fix spelling error in manpage
    Origin: vendor
    Author: Salvatore Bonaccorso <carnil@debian.org>
    Last-Update: 2016-11-10
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libsvn-hooks-perl.git/plain/debian/patches/fix-spelling-error-in-manpage.patch

Thanks for considering,
  Salvatore Bonaccorso,
  Debian Perl Group

**Comment by gnustavo** [comment]
Thanks, Salvatore. I'll apply it in the next release.
