### ISSUE TITLE
[PATCH] Fix spelling errors in manpages

### ISSUE THREAD

**Issue by carnil** [gnustavo/SVN-Hooks#5]
Hi,

In Debian we are currently applying the following patch to SVN-Hooks.
We thought you might be interested in it too.

    Description: Fix spelling errors in manpages
    Origin: vendor
    Author: Salvatore Bonaccorso <carnil@debian.org>
    Last-Update: 2015-08-24
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libsvn-hooks-perl.git/plain/debian/patches/fix-spelling-error-in-manpage.patch

Thanks for considering,
  Salvatore Bonaccorso,
  Debian Perl Group

**Comment by gnustavo** [comment]
Thanks, Salvatore. I fixed it on d2f0529d.
