### ISSUE TITLE
Question: Is is possible to execute the DENY_FILENAMES in a start-commit hook?

### ISSUE THREAD

**Issue by mat060** [gnustavo/SVN-Hooks#8]
when committing a large amount of files or when committing large files, the transaction fails after being transferred (through the network) all the content of the files, at least that is what it seems.

Is it possible to execute the DENY_FILENAMES plugin in the star-commit hook so the file name validation occurs before the files are transferred to the server? This to avoid large amount of data to be sent if the transactions is going to be failed at the end.

Thanks in advanced for your answer.

**Comment by gnustavo** [comment]
Hi Mat,

Yes, it would be very nice indeed if we could do checks on the list of changed files in a commit in the start-commit hook. The [check-filesize-limit](https://github.com/gnustavo/SVN-Hooks/blob/master/examples/check-filesize-limit.pl) example is a good fit for that.

Unfortunately, during the start-commit hook we don't know yet what files are being changed in the commit.

In fact I just learned that Subversion 1.8 changed the start-commit hook to pass a new argument to it. Now it gets the name of the commit transaction, exactly what we need to inspect the commit being performed. However, I tested it and I couldn't get the list of changed files using the following command in the hook:

    svnlook -t TXN changed REPOPATH

Hence, so far as I can tell, it's still not possible to do any checks involving the files being changed by a commit in the start-commit hook.

Please, tell me if you know any better, ok?

**Comment by mat060** [comment]
Thanks a lot for your answer. Well, hopefully we can work around this in the next version of SVN.

Thanks for your advise. I will let you know if I find anything else.
