### ISSUE TITLE
[PATCH] Fix spelling errors in manpage

### ISSUE THREAD

**Issue by carnil** [gnustavo/SVN-Hooks#9]
Hi,

In Debian we are currently applying the following patch to SVN-Hooks.
We thought you might be interested in it too.

    Description: Fix spelling errors in manpage
    Origin: vendor
    Author: Salvatore Bonaccorso <carnil@debian.org>
    Last-Update: 2016-07-19
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libsvn-hooks-perl.git/plain/debian/patches/spelling-error-in-manpage.patch

Thanks for considering,
  Salvatore Bonaccorso,
  Debian Perl Group

**Comment by gnustavo** [comment]
Thank you, Salvatore. It'll be included in the next release.
